version: "1.0"
info:
  model: int-scaffold
packages:
- name: LocalDatabaseProject
  gitServerName: KritikasGitHubAccount
  gitUrl: https://github.com/KitNabber/LocalDatabaseProject
  gitUsername: KitNabber
  gitBranch: main
- name: WmJDBCAdapter
  wpmServer: https://packages.softwareag.com
  wpmRegistry: softwareag
services:
- serviceName: project.localdatabase.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections:mysqldatabase
  packages:
  - name: LocalDatabaseProject
    version: "1.0"
- serviceName: project.localdatabase.integrations:createanAPI
  packages:
  - name: LocalDatabaseProject
    version: "1.0"
- serviceName: project.localdatabase.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.operations.actions:Mysql
  packages:
  - name: LocalDatabaseProject
    version: "1.0"
- serviceName: pub.flow:debugLog
  packages:
  - name: WmPublic
    version: 11.0.0.0.656
- serviceName: project.localdatabase.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections:discountdbconector
  packages:
  - name: LocalDatabaseProject
    version: "1.0"
configurationVariables:
  ? artConnection.LocalDatabaseProject.project.localdatabase.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.mysqldatabase.connectionSettings.databaseName
  : origindemodb
  ? artConnection.LocalDatabaseProject.project.localdatabase.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.mysqldatabase.connectionSettings.otherProperties
  : loginTimeout=60;
  ? artConnection.LocalDatabaseProject.project.localdatabase.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.discountdbconector.connectionEnabled
  : "false"
  ? artConnection.LocalDatabaseProject.project.localdatabase.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.discountdbconector.connectionManagerSettings.poolable
  : "false"
  ? artConnection.LocalDatabaseProject.project.localdatabase.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.discountdbconector.connectionSettings.keyStore
  : ""
  ? artConnection.LocalDatabaseProject.project.localdatabase.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.mysqldatabase.connectionEnabled
  : "false"
  ? artConnection.LocalDatabaseProject.project.localdatabase.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.discountdbconector.connectionManagerSettings.minimumPoolSize
  : "0"
  ? artConnection.LocalDatabaseProject.project.localdatabase.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.mysqldatabase.connectionSettings.trustStore
  : ""
  ? artConnection.LocalDatabaseProject.project.localdatabase.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.discountdbconector.connectionManagerSettings.maximumPoolSize
  : "10"
  ? artConnection.LocalDatabaseProject.project.localdatabase.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.mysqldatabase.connectionSettings.portNumber
  : "3306"
  ? artConnection.LocalDatabaseProject.project.localdatabase.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.discountdbconector.connectionSettings.networkProtocol
  : tcp
  ? artConnection.LocalDatabaseProject.project.localdatabase.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.discountdbconector.connectionSettings.datasourceClass
  : com.mysql.cj.jdbc.MysqlDataSource
  ? artConnection.LocalDatabaseProject.project.localdatabase.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.discountdbconector.connectionSettings.databaseName
  : OriginDemo
  ? artConnection.LocalDatabaseProject.project.localdatabase.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.mysqldatabase.connectionSettings.keyStore
  : ""
  ? artConnection.LocalDatabaseProject.project.localdatabase.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.mysqldatabase.connectionManagerSettings.startupBackoffSecs
  : "10"
  ? artConnection.LocalDatabaseProject.project.localdatabase.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.discountdbconector.connectionManagerSettings.startupBackoffSecs
  : "10"
  ? artConnection.LocalDatabaseProject.project.localdatabase.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.discountdbconector.connectionSettings.driverType
  : sqldriver
  ? artConnection.LocalDatabaseProject.project.localdatabase.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.mysqldatabase.connectionSettings.password
  : "{AES}q6MgwtyfSQqk72HtldIMMQ=="
  ? artConnection.LocalDatabaseProject.project.localdatabase.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.mysqldatabase.connectionSettings.datasourceClass
  : com.mysql.cj.jdbc.MysqlDataSource
  ? artConnection.LocalDatabaseProject.project.localdatabase.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.mysqldatabase.connectionSettings.networkProtocol
  : tcp
  ? artConnection.LocalDatabaseProject.project.localdatabase.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.mysqldatabase.connectionManagerSettings.startupRetryCount
  : "0"
  ? artConnection.LocalDatabaseProject.project.localdatabase.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.mysqldatabase.connectionManagerSettings.poolIncrementSize
  : "1"
  ? artConnection.LocalDatabaseProject.project.localdatabase.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.mysqldatabase.connectionSettings.serverName
  : 172.20.240.1
  ? artConnection.LocalDatabaseProject.project.localdatabase.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.discountdbconector.connectionManagerSettings.blockingTimeout
  : "1000"
  ? artConnection.LocalDatabaseProject.project.localdatabase.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.mysqldatabase.connectionManagerSettings.expireTimeout
  : "1000"
  ? artConnection.LocalDatabaseProject.project.localdatabase.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.discountdbconector.connectionSettings.password
  : "{AES}PXMlRlh5l1Gh0SvCKBs8h99C6Px/E1onyRQ1j1CQlRE="
  ? artConnection.LocalDatabaseProject.project.localdatabase.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.discountdbconector.connectionManagerSettings.startupRetryCount
  : "0"
  ? artConnection.LocalDatabaseProject.project.localdatabase.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.mysqldatabase.connectionSettings.dbType
  : MySQL
  ? artConnection.LocalDatabaseProject.project.localdatabase.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.mysqldatabase.connectionSettings.user
  : rawa
  ? artConnection.LocalDatabaseProject.project.localdatabase.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.discountdbconector.connectionSettings.user
  : root
  ? artConnection.LocalDatabaseProject.project.localdatabase.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.discountdbconector.connectionSettings.otherProperties
  : loginTimeout=60;
  ? artConnection.LocalDatabaseProject.project.localdatabase.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.discountdbconector.connectionSettings.trustStore
  : ""
  ? artConnection.LocalDatabaseProject.project.localdatabase.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.discountdbconector.connectionSettings.serverName
  : 95.223.74.241
  ? artConnection.LocalDatabaseProject.project.localdatabase.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.mysqldatabase.connectionManagerSettings.heartBeatInterval
  : "0"
  ? artConnection.LocalDatabaseProject.project.localdatabase.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.mysqldatabase.connectionManagerSettings.blockingTimeout
  : "1000"
  ? artConnection.LocalDatabaseProject.project.localdatabase.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.mysqldatabase.connectionSettings.driverType
  : sqldriver
  ? artConnection.LocalDatabaseProject.project.localdatabase.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.mysqldatabase.connectionManagerSettings.maximumPoolSize
  : "10"
  ? artConnection.LocalDatabaseProject.project.localdatabase.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.mysqldatabase.connectionManagerSettings.minimumPoolSize
  : "0"
  ? artConnection.LocalDatabaseProject.project.localdatabase.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.discountdbconector.connectionManagerSettings.heartBeatInterval
  : "0"
  ? artConnection.LocalDatabaseProject.project.localdatabase.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.discountdbconector.connectionManagerSettings.expireTimeout
  : "1000"
  ? artConnection.LocalDatabaseProject.project.localdatabase.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.discountdbconector.connectionSettings.transactionType
  : NO_TRANSACTION
  ? artConnection.LocalDatabaseProject.project.localdatabase.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.discountdbconector.connectionSettings.portNumber
  : "3306"
  ? artConnection.LocalDatabaseProject.project.localdatabase.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.discountdbconector.connectionSettings.dbType
  : MySQL
  ? artConnection.LocalDatabaseProject.project.localdatabase.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.mysqldatabase.connectionManagerSettings.poolable
  : "false"
  ? artConnection.LocalDatabaseProject.project.localdatabase.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.discountdbconector.connectionManagerSettings.poolIncrementSize
  : "1"
  ? artConnection.LocalDatabaseProject.project.localdatabase.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.mysqldatabase.connectionSettings.transactionType
  : NO_TRANSACTION
